version: '3'

services:
  apibnk:
    image: apibnk
    command: >
            bash -c "mix ecto.create &&
                    mix ecto.migrate && mix phx.server"
    ports:
      - "4000:4000"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:9.6-alpine
    restart: always
