version: '3'

services:
  apibnk:
    image: apibnk
    command: >
            bash -c "mix ecto.create &&
                    mix ecto.migrate && mix phx.server"
    ports:
      - "4000:4000"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:10.9-alpine
    restart: always
